[package]
name = "pg-queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.188"
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["postgres", "migrate"] }
